HumanResources/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :users do 
    member do
      get 'my_center'
      get 'new_detail'
      post 'create_detail'
    end
  end

  mount API => "/"
end

HumanResources/app/models/setting.rb
# -*- encoding : utf-8 -*-
class Setting <  ActiveRecord::Base

  def self.all_careers
    result = {}
    Setting.where("name = ?",'career').map do|career|
      result[career.value] = career.setting_key  
    end
    return result
  end
end

HumanResources/app/models/user.rb
# -*- encoding : utf-8 -*-
class User <  ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :set_user_name


  def set_user_name
    self.user_name = self.email.split("@")[0]
  end

  #key是关键字，需要使用`key`
  def career_name
    career = Setting.where("name = ? and setting_key = ?", "career", self.career).first
    career.value if career
  end

  def career_years_name
    default = {"1年" => 1,
      "1-3年" => 2,
      "3-5年" => 3,
      "5-10年" => 4,
      "10年以上" => 5}
    self.career_years ? default.keys[self.career_years] : ""
  end
end

HumanResources/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :configure_permitted_parameters, if: :devise_controller?


  # protected
  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.for(:sign_up) << :career
  # end
end

HumanResources/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

HumanResources/app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

HumanResources/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

HumanResources/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

HumanResources/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

HumanResources/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

HumanResources/app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

HumanResources/app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'my_center', :only => [:my_center, :new_detail]
  def show
    @user = User.find(params[:id])
  end

  def my_center
    @user = User.find(params[:id])
  end

  def new_detail
    @user = User.find(params[:id])
  end

  def create_detail
    @user = User.find(params[:id])
    @user.update_attributes(career: params[:user][:career], career_years: params[:user][:career_years], desc: params[:user][:desc])
    redirect_to my_center_user_path(@user)
  end

  protected

  def user_params
    params.require(:user).permit(:career, :career_years, :desc)
  end
end

HumanResources/app/helpers/application_helper.rb
module ApplicationHelper
end

HumanResources/app/helpers/users_helper.rb
module UsersHelper

  def career_years_options
    {"1年" => 1,
      "1-3年" => 2,
      "3-5年" => 3,
      "5-10年" => 4,
      "10年以上" => 5}
  end
end

HumanResources/app/views/home/index.html.erb
<% content_for :content_body do %>
  fuck you!
  <% if user_signed_in? %>
    <%= link_to current_user.user_name, my_center_user_path(current_user) %>
    <%= link_to 'logout', destroy_user_session_path, :method => :delete %>
  <% else %>
    <%=link_to '登录', new_user_session_path %>
  <% end %>
<%end %>

HumanResources/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HumanResources</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

HumanResources/app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <title>HumanResources</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield :content_body %>

</body>
</html>

HumanResources/app/views/layouts/my_center.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <title>用户中心</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
        <div class="row-fluid">
          <div class="col-xs-2">
            <img alt="140x140" src="img/a.jpg" />
          </div>
          <div class="col-xs-10">
          基本信息<br/>
          用户：<%= @user.user_name%><br/>
          Email：<%= @user.email%><br/>
          </div>
        </div>
        <div class="row-fluid">
          <div class="col-xs-2">
            <ul>
              <li>详细信息</li>
            </ul>
          </div>
          <div class="col-xs-10">
            <%= yield :my_center_detail %>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

HumanResources/app/views/users/my_center.html.erb
<% content_for :my_center_detail do %>
  <% if @user.career %>
    <fieldset>
       <legend>职业信息</legend> 
       <p><label>职业： </label><%= @user.career_name %></p>
       <p><label>从业时间： </label><%= @user.career_years_name %></p>
       <p><label>自我简介： </label><%= @user.desc %></p>
    </fieldset>
  <% else %>
    立刻补充信息，让别人找到你：<%= link_to '补充信息', new_detail_user_path(current_user) %>
  <% end %>
<%end %>

HumanResources/app/views/users/new_detail.html.erb
<% content_for :my_center_detail do %>
  <%= form_for @user, :url => create_detail_user_path(@user), :method => :post do|f| %>
    <fieldset>
       <legend>职业信息</legend> 
       <p><label>职业： </label><%= f.select :career, options_for_select(Setting.all_careers) %></p>
       <p><label>从业时间： </label><%= f.select :career_years, options_for_select(career_years_options) %></p>
       <p><label>自我简介： </label><%= f.text_area :desc, :size=>"20x5" %></p>
       
       <button type="submit" class="btn">提交</button>
    </fieldset>
  <% end %>
<%end %>